name: flutter_seller_fic7
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.0
  money_formatter: ^0.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
